threatgraph:
  input:
    redis:
      addr: 127.0.0.1:6379
      password: ""
      db: 0
      key: sysmon_events
      block_timeout: 5s

  pipeline:
    workers: 8
    batch_size: 1000
    flush_interval: 2s

  rules:
    enabled: false
    path: "./rules/sigma"

  output:
    mode: file
    file:
      path: output/adjacency.jsonl

  # Lightweight IOA stream output for stage-1 sequence prefiltering.
  ioa:
    enabled: true
    output:
      mode: clickhouse
      file:
        path: output/ioa_events.jsonl
      clickhouse:
        url: http://127.0.0.1:8123
        database: threatgraph
        table: ioa_events
        username: default
        password: ""
        timeout: 5s
        headers: {}

  replay_capture:
    enabled: false
    file:
      path: output/raw_events.jsonl
    batch_size: 1000
    flush_interval: 2s

  vertex_state:
    enabled: true
    redis:
      addr: 127.0.0.1:6379
      password: ""
      db: 0
    key_prefix: threatgraph:vertex_state
    scan_interval: 30s
    lookback: 5m

  logging:
    enabled: true
    level: info
    file: ""
    console: true
